### ISSUE TITLE
Stopping results in a crash

### ISSUE THREAD

**Issue by joonas-fi** [function61/pi-security-module#21]
```
Sep 18 08:47:40 raspberrypi systemd[1]: Stopping Pi security module...
Sep 18 08:47:40 raspberrypi pism[11749]: 2018/09/18 08:47:40 Received signal terminated; shutting down
Sep 18 08:47:40 raspberrypi pism[11749]: 2018/09/18 08:47:40 Closing stream log
Sep 18 08:47:40 raspberrypi pism[11749]: panic: runtime error: invalid memory address or nil pointer dereference
Sep 18 08:47:40 raspberrypi pism[11749]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x2412cc]
Sep 18 08:47:40 raspberrypi pism[11749]: goroutine 1 [running]:
Sep 18 08:47:40 raspberrypi pism[11749]: net/http.(*Server).Shutdown(0x12660300, 0x0, 0x0, 0x0, 0x0)
Sep 18 08:47:40 raspberrypi pism[11749]: /usr/local/go/src/net/http/server.go:2581 +0x160
Sep 18 08:47:40 raspberrypi pism[11749]: main.runMain()
Sep 18 08:47:40 raspberrypi pism[11749]: /go/src/github.com/function61/pi-security-module/cmd/pism/main.go:79 +0x320
Sep 18 08:47:40 raspberrypi pism[11749]: main.serverEntrypoint.func1(0x126943c0, 0x89c16c, 0x0, 0x0)
Sep 18 08:47:40 raspberrypi pism[11749]: /go/src/github.com/function61/pi-security-module/cmd/pism/main.go:94 +0x14
Sep 18 08:47:40 raspberrypi pism[11749]: github.com/function61/pi-security-module/vendor/github.com/spf13/cobra.(*Command).execute(0x126943c0, 0x89c16
Sep 18 08:47:40 raspberrypi pism[11749]: /go/src/github.com/function61/pi-security-module/vendor/github.com/spf13/cobra/command.go:766 +0x20c
Sep 18 08:47:40 raspberrypi pism[11749]: github.com/function61/pi-security-module/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x12694280, 0x1269
Sep 18 08:47:40 raspberrypi pism[11749]: /go/src/github.com/function61/pi-security-module/vendor/github.com/spf13/cobra/command.go:852 +0x20c
Sep 18 08:47:40 raspberrypi pism[11749]: github.com/function61/pi-security-module/vendor/github.com/spf13/cobra.(*Command).Execute(0x12694280, 0x12767
Sep 18 08:47:40 raspberrypi pism[11749]: /go/src/github.com/function61/pi-security-module/vendor/github.com/spf13/cobra/command.go:800 +0x1c
Sep 18 08:47:40 raspberrypi pism[11749]: main.main()
Sep 18 08:47:40 raspberrypi pism[11749]: /go/src/github.com/function61/pi-security-module/cmd/pism/main.go:130 +0x14c
Sep 18 08:47:40 raspberrypi systemd[1]: pi-security-module.service: main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by joonas-fi** [comment]
I have only witnessed this on the Raspberry. The last time it happened when I was upgrading the version

**Comment by joonas-fi** [comment]
Turns out it was due to missing context to `httpServer.Shutdown()`, which only crashes sometimes 🤦‍♂️
